In [1]:
import numpy as np
class Array:
    def main():
        arr_1=np.array([1,2,3,4,5,6,7,8,9,10])
        arr_2=[1,2,3,4,5,6,7,8,9,10]
        arr_3=(1,2,3,4,5,6,7,8,9,10)
        arr_4={1,2,3,4,5,6,7,8,9,10}
        arr_5={
            "name":"google",
            "age":"100",
            "type":"search engine",
            "player":"youtube",
        }
        print(arr_1,type(arr_1))
        print(arr_2,type(arr_2))
        print(arr_3,type(arr_3))
        print(arr_4,type(arr_4))
        print(arr_5,type(arr_5))
    main()
obj_array=Array()

[ 1  2  3  4  5  6  7  8  9 10] <class 'numpy.ndarray'>
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10] <class 'list'>
(1, 2, 3, 4, 5, 6, 7, 8, 9, 10) <class 'tuple'>
{1, 2, 3, 4, 5, 6, 7, 8, 9, 10} <class 'set'>
{'name': 'google', 'age': '100', 'type': 'search engine', 'player': 'youtube'} <class 'dict'>


In [2]:
#To check system's python numpy library version
import numpy as np
print(np.__version__)

1.22.4


In [6]:
import numpy as np
class Array_dimension:
    def main():
        arr_1=np.array(25)
        arr_2=np.array([1,2,3])
        arr_3=np.array([[1,2,3],[4,5,6]])
        arr_4=np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])
        print(arr_1,arr_1.ndim)
        print("\n")
        print(arr_2,arr_2.ndim)
        print("\n")
        print(arr_3,arr_3.ndim)
        print("\n")
        print(arr_4)
        print("\n")
        print(arr_4.ndim)
Array_dimension.main()

        

25 0


[1 2 3] 1


[[1 2 3]
 [4 5 6]] 2


[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


3


In [8]:
import numpy as np
arr=np.array([2,45,6,85,4,4,6,64,89,746,6,84,5],ndmin=5)
print(arr)
print(arr.ndim)

[[[[[  2  45   6  85   4   4   6  64  89 746   6  84   5]]]]]
5


In [20]:
import numpy as np
class Test:
    def main_1():
        arr_1=np.array([1,2,3,4,5,67,8,90])
        print("Index/Address of elements -> ",arr_1[1])
        print("Addition of arrays elements using index value = ",arr_1[0]+arr_1[1])
    def main_2():
        arr_2=np.array([[1,2,3,33],[4,5,6,66]])
        print(arr_2[1,2])
        print(arr_2[0,3])
    def main_3():
        arr_3=np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])
        print(arr_3[2,0,1])
Test.main_1()
Test.main_2()
Test.main_3()
        
        

Index/Address of elements ->  2
Addition of arrays elements using index value =  3
6
33
10


In [24]:
class Test:
    def main():
        list_1=[]
        n=int(input("Enter the number of array elements -> "))
        for x in range(0,n):
            m=int(input())
            list_1.append(m)
        print(list_1)
        print(type(list_1))
        list_1.sort()
        print("Ascending Order ->",list_1)
        list_1.sort(reverse=True)
        print("Descending Order -> ",list_1)
obj_list=Test
obj_list.main()

[111, 565, 22, 9696, 458, 98, 888, 22, 1, 2256]
<class 'list'>
Ascending Order -> [1, 22, 22, 98, 111, 458, 565, 888, 2256, 9696]
Descending Order ->  [9696, 2256, 888, 565, 458, 111, 98, 22, 22, 1]


In [40]:
import random 
import numpy as np
class Array_random():
    def main_1():
        arr_1=np.random.randint(20,90,20)
        print(arr_1)
obj_array=Array_random
obj_array.main_1()

[60 83 66 63 46 71 67 40 38 29 84 44 85 49 61 27 49 20 53 57]
